// The `theme` value MUST match a daisyUI theme name registered in
// tailwind.config.js — daisyUI applies it via the form's `data-theme`
// attribute. The color fields below are only used for the swatch preview.
export default [
  {
    "color-scheme": "dark",
    primary: "#09ecf3",
    secondary: "#966fb3",
    accent: "#ffe999",
    neutral: "#3b8ac4",
    theme: "aqua",
  },
  {
    "color-scheme": "dark",
    primary: "#ff865b",
    secondary: "#fd6f9c",
    accent: "#b387fa",
    neutral: "#1c1917",
    theme: "sunset",
  },
  {
    "color-scheme": "dark",
    primary: "#38bdf8",
    secondary: "#818cf8",
    accent: "#f471b5",
    neutral: "#1e293b",
    theme: "night",
  },
  {
    "color-scheme": "dark",
    primary: "#e779c1",
    secondary: "#58c7f3",
    accent: "#f3cc30",
    neutral: "#20134e",
    theme: "synthwave",
  },
  {
    "color-scheme": "light",
    primary: "#ff7598",
    secondary: "#75d1f0",
    accent: "#c07eec",
    neutral: "#423f00",
    theme: "cyberpunk",
  },
  {
    "color-scheme": "dark",
    primary: "#ff79c6",
    secondary: "#bd93f9",
    accent: "#ffb86c",
    neutral: "#414558",
    theme: "dracula",
  },
  {
    "color-scheme": "light",
    primary: "#e96d7b",
    secondary: "#a991f7",
    accent: "#88dbdd",
    neutral: "#af4670",
    theme: "valentine",
  },
  {
    "color-scheme": "light",
    primary: "#ef9995",
    secondary: "#a4cbb4",
    accent: "#dc8850",
    neutral: "#2e282a",
    theme: "retro",
  },
  {
    "color-scheme": "dark",
    primary: "#1eb854",
    secondary: "#1db990",
    accent: "#1db9ac",
    neutral: "#19362d",
    theme: "forest",
  },
  {
    "color-scheme": "dark",
    primary: "#ffffff",
    secondary: "#152747",
    accent: "#513448",
    neutral: "#171618",
    theme: "luxury",
  },
  {
    "color-scheme": "dark",
    primary: "#db924b",
    secondary: "#263e3f",
    accent: "#10576d",
    neutral: "#120c12",
    theme: "coffee",
  },
  {
    "color-scheme": "light",
    primary: "#65c3c8",
    secondary: "#ef9fbc",
    accent: "#eeaf3a",
    neutral: "#291334",
    theme: "cupcake",
  },
  {
    "color-scheme": "light",
    primary: "#66cc8a",
    secondary: "#377cfb",
    accent: "#ea5234",
    neutral: "#333c4d",
    theme: "emerald",
  },
  {
    "color-scheme": "light",
    primary: "#8c0327",
    secondary: "#d85251",
    accent: "#d59b6a",
    neutral: "#826a5c",
    theme: "autumn",
  },
  {
    "color-scheme": "light",
    primary: "#047aff",
    secondary: "#463aa2",
    accent: "#c148ac",
    neutral: "#021431",
    theme: "winter",
  },
  {
    "color-scheme": "light",
    primary: "#5e81ac",
    secondary: "#81a1c1",
    accent: "#88c0d0",
    neutral: "#4c566a",
    theme: "nord",
  },
  {
    "color-scheme": "light",
    primary: "#1c4e80",
    secondary: "#7c909a",
    accent: "#ea6947",
    neutral: "#23282e",
    theme: "business",
  },
];
